# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1625O-4ABzbVrwJRwmhZZm7bSn7etDWGT

# IMPORT LIBRARY
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.decomposition import PCA
import time

!gdown '1X84DREbk1dUTyDYWxRHvueSktlvy5yg6' --output data.csv

# read csv data
dataset = pd.read_csv('data.csv')

dataset.head()

"""# View Data That is Null"""

dataset.isnull().sum()

"""# View Data Information"""

dataset.info()

"""# Delete Data"""

# Select the column to be deleted
columns_to_drop = ['garis_kemiskinan','tidak_bekerja.1',
                   'pengeluaran_makanan_total']
# Delete columns using the drop method and set axis=1
dataset = dataset.drop(columns_to_drop, axis=1)
# Viewing the results of deleted variables
dataset

"""# Replace Data and Change Data Types

"""

# Counting the number of “-” values in the entire dataset
count_min = (dataset == '-').sum().sum()
count_min

# Replace the character “-” with the value 'NaN'
dataset.replace('-', np.nan, inplace=True)

# Change the data type of objects to float from several columns
dataset[['tamat_kurang_sd','bekerja_formal', 'bekerja_pertanian',
         'bekerja_bukan_pertanian']] = dataset[['tamat_kurang_sd','bekerja_formal', 'bekerja_pertanian',
         'bekerja_bukan_pertanian']].astype(float)

# Print the DataFrame to see the changes
dataset.info()

"""# Imputation Using The Average each Column

"""

# Imputation according to the average per column
for column in dataset.columns:
    if dataset[column].isnull().any():  # Checking whether there are null values in the column
        mean_value = dataset[column].mean() # Calculating the average of all columns
        dataset[column].fillna(mean_value, inplace=True) # Fill in the blank columns with averages
        print(f"\nKolom {column} diimputasi dengan rata-rata {mean_value:.2f}")

# Checking the result of imputation
dataset.info()

"""# View Data Statistic"""

dataset.describe().T

"""# Viewing the Number of Outliers in Each Column

"""

# Function to calculate outliers based on the IQR method
def calculate_outlier(dataset):
    outliers = {}  # Dictionary to store the number of outliers each columns
    for column in dataset.select_dtypes(include=['float64', 'int64']).columns:  # Cek hanya column numerik
        # Calculating Q1 and Q3
        Q1 = dataset[column].quantile(0.25)
        Q3 = dataset[column].quantile(0.75)
        # Calculating IQR
        IQR = Q3 - Q1
        # Determining the lower and upper limits for outliers
        lower_limit = Q1 - 1.5 * IQR
        upper_limit = Q3 + 1.5 * IQR

        # Calculating the outlier
        outlier = dataset[(dataset[column] < lower_limit) | (dataset[column] > upper_limit)].shape[0]

        # Save to dictionary
        outliers[column] = outlier

    return outliers

# Create object to store the outlier calculations
outlier_count = calculate_outlier(dataset)

# Display the number of outliers per column in vertical format
print("Number of Outliers per Column:")
for column, number_of_outlier in outlier_count.items():
    print(f"{column}: {number_of_outlier}")

"""# Performing Scaling using Robust

"""

# Selecting Numeric Column
X = dataset.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]].values
X

from sklearn.preprocessing import RobustScaler

# Create RobustScaler Object
scaler = RobustScaler()

# Implementation Robust Scaler to Data
data_scaled = scaler.fit_transform(X)

pd_data = pd.DataFrame(data_scaled)
pd_data

"""# Corellation Analys"""

# Calculate the correlation between numeric columns
corelattion = pd_data.corr()

# print(corelattion)
# Create a heatmap from correlation metrics
plt.figure(figsize=(10, 8))
sns.heatmap(corelattion, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation between Numeric Columns')
plt.show()

"""There appears to be a high correlation between several variables.

# PCA Process
"""

pca = PCA().fit(pd_data)

# Take the explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

# Hitung varians kumulatif
cumulative_variance = np.cumsum(explained_variance_ratio)

# Calculate the cumulative variance
three_component_variance = cumulative_variance[3]  #
print(f'Cumulative explained variance for 3 components: {three_component_variance:.4f}')

# Visualization
plt.figure(figsize=(6, 4))
plt.plot(cumulative_variance, marker='o')
plt.axvline(x=3, color='r', linestyle='--')
plt.title('Cumulative Explained Variance')
plt.xlabel('Number of components')
plt.ylabel('Cumulative explained variance')
plt.xlim(0, len(cumulative_variance)-1)
plt.ylim(0, 1)
plt.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.7)
plt.show()

# Create 3 PCA Components
pca = PCA(n_components=3)

# Fit PCA on standardised data and data transformation
X_pca = pca.fit_transform(pd_data)

# Take the components and variance ratios described
data_pca = pca.components_

# Creating a DataFrame for 3 components
components_df = pd.DataFrame(data = data_pca, columns=[f'Feature {i+1}' for i in range(data_scaled.shape[1])])
components_df.index = [f'PC {i+1}' for i in range(data_pca.shape[0])]

# View result table
print(" PCA Components:")
print(components_df)

# Create a new DataFrame with the PCA results
pca_df = pd.DataFrame(data=X_pca , columns=['PCA1', 'PCA2','PCA3'])

# View PCA result
pca_df

"""# Merge Initial Dataset (district column) with PCA Results Data"""

# Select the desired column
selected_data1 = dataset[['kabupaten']]
selected_data2 = pca_df[['PCA1', 'PCA2','PCA3']]

# Vertically combine
combined_data = pd.concat([selected_data1, selected_data2], axis=1, ignore_index=True)

# Changing column names after merging
combined_data.columns = ['kabupaten', 'PCA1', 'PCA2','PCA3']

# View the result
print("Vertical Combined Data : ")
print(combined_data)

from google.colab import files
# Simpan DataFrame ke file CSV
file_name = 'hasil_preprocessing.csv'
combined_data.to_csv(file_name, index=False)

# Unduh file ke komputer lokal
files.download(file_name)